on: 
  push:
    branches: [ main ]

jobs:
  deploy_to_aeweb:
    runs-on: ubuntu-latest
    name: A job to deploy file to AEweb | mainnet network
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to AEweb
        id: deploy
        uses: archethic-foundation/aeweb-github-action@v1.5.4
        with:
          seed: ${{ secrets.ARCH_BASE_MAINNET_SEED }}
          endpoint: "https://mainnet.archethic.net"
          path: "." 