on: 
  push:
    branches: [ preprod ]

jobs:
  deploy_to_aeweb:
    runs-on: ubuntu-latest
    name: A job to deploy file to AEweb | testnet network
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to AEweb
        id: deploy
        uses: archethic-foundation/aeweb-github-action@develop
        with:
          seed: ${{ secrets.ARCH_BASE_TESTNET_SEED }}
          endpoint: "https://testnet.archethic.net"
          path: "." 
          keychainFundingService: "archethic-wallet-ARCHETHIC.NET"
          keychainWebsiteService: "aeweb-ARCHETHIC-website"
          sslCertificateFile: "./cert.pem"
          sslKey: ${{ secrets.SSL_KEY }}
